version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cp client/package.json .
      - cd client
      - npm install
      - cd ..
  build:
    commands:
      - cd client
      - npm run build
      - cd ..
artifacts:
  files:
    - '**/*'
  base-directory: 'client/build'
